### PR TITLE
Add input to allow values outside slider range & add co2 figures

### PR DESCRIPTION
**Pull request by CNimmo16**
Implement requested feature from issue #84. Input box appears when slider value is above zero. I've moved the input box to be below the slider because for elements with multiple dimensions, the previous slider label placement was confusing.

### CODE REVIEW

**Comment by CNimmo16** [comment]
Also includes fix for a bug in all elements with 3 dimensions, causing incorrect data to be shown for one of the three inputs

**Comment by edanweis** [comment]
Great, looks much better. Can you please adjust the padding and unset max width for the input box? like this: 
image

I don't understand what data what shown as incorrect for one of the three inputs for items with 3 dimensions.

**Comment by pjconrad** [comment]
The units for width should be in inches, not feet per the spreadsheet.

**Comment by CNimmo16** [comment]
Yes, I'll get those styling changes put in. See attached image of 3 dimension element from the live site. Second and third array indexes for "dimension" are set up as [0] and [1] instead of [1] and [2] respectively.
Screenshot from 2019-09-04 15-39-30

**Comment by CNimmo16** [comment]
> The units for width should be in inches, not feet per the spreadsheet.
> […](#)
> On Sep 4, 2019, at 6:35 AM, Edan Weis ***@***.***> wrote: Great, looks much better. Can you please adjust the padding and unset max width for the input box? like this: I don't understand what data what shown as incorrect for one of the three inputs for items with 3 dimensions. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Fixed in metadata schema

**Comment by CNimmo16** [comment]
> The units for width should be in inches, not feet per the spreadsheet.
> […](#)
> On Sep 4, 2019, at 6:35 AM, Edan Weis ***@***.***> wrote: Great, looks much better. Can you please adjust the padding and unset max width for the input box? like this: I don't understand what data what shown as incorrect for one of the three inputs for items with 3 dimensions. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Fixed in metadata schema

**Comment by CNimmo16** [comment]
Updated to include implementation of #95

**Pull request merged**
