### PR TITLE
fix banner image sizing issues on project edit page

### PR DESCRIPTION
**Pull request by CNimmo16**
Fix for banner sizing problems on desktop project edit page - referenced in issue #78.

### CODE REVIEW

**Comment by CNimmo16** [comment]
Thumbnail fetched from api was being used instead of the actual image on the project page. I've swapped it out for the main image, falling back to the thumbnail if main image isn't available (which seems to be the case with many of the images)

**Comment by edanweis** [comment]
> (which seems to be the case with many of the images)
I remember caching the Bing API response by storing the image URLs in Firebase to minimise API calls. Are you sure they're not failing because images of old projects are cached with some kind of `thumbnail` query parameter in them? Does this still happen with new projects? Whats the API response when it fails?

**Comment by CNimmo16** [comment]
No it's not that I don't think, I've checked a couple of the content urls in question and several are simply not available anymore. Eg. http://www.hostelgarden.net/wp-content/uploads/2014/11/colorful-ideas-of-nice-gardens.jpg - site's domain has expired. The api response doesn't fail, it fetches a url, and the image elements try to load it but are unable to, vuetify throws an error. My workaround is just to set the lazy-src as the cached thumbnail to ensure an image is always shown.

**Comment by edanweis** [comment]
The images seem to be reverting after going into edit page, then back out to project summary page. Images also show up blank when going back into the project list page.

**Comment by CNimmo16** [comment]
Fixed the problem with the blank images in list, unfortunately don't have time to fix the images reverting, from a quick look it doesn't look like a single image is ever saved to the project, just an array of image options (I might be wrong)

**Comment by CNimmo16** [comment]
Image reverting bug from #136 seems to have ended up being a super simple fix, @edanweis please see latest commit

**Pull request merged**
